version: '3.8'
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 30s
      timeout: 10s
      retries: 5

  kafka:
      image: docker.io/bitnami/kafka:3.4
      ports:
        - "9092:9092"
      volumes:
        - "kafka_data:/bitnami"
      environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      depends_on:
        zookeeper:
          condition: service_healthy
      healthcheck:
        test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092"]
        interval: 30s
        timeout: 10s
        retries: 5

  video-stream-io:
    build:
      context: .
      dockerfile: ./apps/video-stream-io/Dockerfile
      target: development
    ports:
      - "9090:9090"
    env_file:
      - ./apps/video-stream-io/.env
    environment:
      - BROKER_0_URI=kafka:9092
    volumes:
      - ./:/app
  
  video-transcoder:
    build:
      context: .
      dockerfile: ./apps/video-transcoder/Dockerfile
      target: development
    env_file:
      - ./apps/video-transcoder/.env
    environment:
      - BROKER_0_URI=kafka:9092
    volumes:
      - ./:/home/app/video-transcoder
    depends_on:
      - kafka
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local