export enum KAFKA_SERVICES {
  VIDEO_TRANSCODE_SERVICE = 'VIDEO_TRANSCODE_SERVICE',
  VIDEO_TRANSCODE_SERVICE_CLIENT_ID = 'VIDEO_TRANSCODE_SERVICE_CLIENT_ID',
  VIDEO_TRANSCODE_SERVICE_GROUP_ID = 'VIDEO_TRANSCODE_SERVICE_GROUP_ID',
}

export enum KAFKA_SERVICES_MESSAGES {
  VIDEO_TRANSCODE_MESSAGE = 'VIDEO_TRANSCODE_MESSAGE',
  STOP_VIDEO_TRANSCODE_MESSAGE = 'STOP_VIDEO_TRANSCODE_MESSAGE',
}
